export enum ErrorCode {
    BAD_MESSAGE = 'BAD_MESSAGE',
    BAD_REQUEST = 'BAD_REQUEST',
    REPOSITORY_ERROR = 'REPOSITORY_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export enum StatusCode {
    OK = 200,
    CREATED = 201,
    NOT_FOUND = 404,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    INTERNAL_ERROR = 500,
}
